#!/bin/sh

# Author: Shuhei Hayakawa

this=$(basename $0)
path=$(dirname $(readlink -f $0))
cd $path
version=`git log --pretty=format:'%cd' --date=short -n 1`

#_______________________________________________________________________________
readlink=readlink
if [ `uname` = "AIX" ]; then
    readlink=echo
fi

fullpath1=`$readlink $0`
if [ "$?" -ne "0" ]; then
    fullpath1=$0
else
    if [ ${fullpath1##/} = $fullpath1 ] && [ ${fullpath1##~} = $fullpath1 ]; then
	lpath=`dirname $0`
	fullpath1=$lpath/$fullpath1
    fi
fi
progdir=`dirname $fullpath1`
runningdir=`pwd`
if [ ${progdir##/} != $progdir ] || [ ${progdir##~} != $progdir ]; then
    fullpath=$progdir
else
    if [ $progdir != "." ]; then
	fullpath=$runningdir/$progdir
    else
	fullpath=$runningdir
    fi
fi

fullpath1=`$readlink $fullpath`
if [ "$?" -ne "0" ]; then
    fullpath1=$fullpath
fi

#_______________________________________________________________________________
prefix=`dirname $fullpath1`
bindir=$prefix/bin
incdir=$prefix/include
libdir=$prefix/lib

usage="Usage: $this [--prefix] [--include] [--libs]\
 [--bindir] [--incdir] [--libdir] [--help] [--version]"

include=-I$incdir
libs="-Wl,-rpath,$libdir -L$libdir"
### core libs
libs="$libs -lHDDAQUnpacker"
libs="$libs -lUnpackerConfig"
libs="$libs -lUnpackerManager"
libs="$libs -lUnpacker"
### util libs
libs="$libs -lfilesystem_util"
libs="$libs -lreplace_string"
libs="$libs -lstd_ostream"
### ext libs
libs="$libs -lxerces-c"

#_______________________________________________________________________________
if test $# -eq 0; then
    echo $usage 1>&2
    exit 1
fi

out=""

while test $# -gt 0; do
    case "$1" in
	-*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
	*)    optarg= ;;
    esac

    case $1 in
	--prefix)
	    out=$prefix
	    ;;
	--include)
	    out=$include
	    ;;
	--libs)
	    out=$libs
	    ;;
	--bindir)
	    out=$bindir
	    ;;
	--libdir)
	    out=$libdir
	    ;;
	--incdir)
	    out=$incdir
	    ;;
	--help)
	    echo "Usage: $this [options]"
	    echo ""
	    echo "  --prefix              Print prefix"
	    echo "  --include             Print header path"
	    echo "  --libs                Print regular Unpacker libraries"
	    echo "  --bindir              Print executable directory"
	    echo "  --incdir              Print header directory"
	    echo "  --libdir              Print library directory"
	    echo "  --help                Print this message"
	    echo "  --version             Print Unpacker version"
	    echo
	    exit 0
	    ;;
	--version)
	    out=$version
	    ;;
	*)
	    echo "Unknown argument \"$1\"!" 1>&2
	    echo "${usage}" 1>&2
	    exit 1
	    ;;
    esac
    shift
done

echo $out
